@include('admin.layouts.header')
@include('admin.layouts.navbar')
@include('admin.layouts.menu')
@include('admin.layouts.messages')

@yield('content')
@push('js')
    <script>
        (function ($) {
            $(function () {
                var isoCountries = [
                     {id: 'AW', text: 'آروبا'},
                    {id: 'AZ', text: 'أذربيجان'},
                    {id: 'AM', text: 'أرمينيا'},
                    {id: 'ES', text: 'أسبانيا'},
                    {id: 'AU', text: 'أستراليا'},
                    {id: 'AF', text: 'أفغانستان'},
                    {id: 'AL', text: 'ألبانيا'},
                    {id: 'DE', text: 'ألمانيا'},
                    {id: 'AG', text: 'أنتيجوا وبربودا'},
                    {id: 'AO', text: 'أنجولا'},
                    {id: 'AI', text: 'أنجويلا'},
                    {id: 'AD', text: 'أندورا'},
                    {id: 'UY', text: 'أورجواي'},
                    {id: 'UZ', text: 'أوزبكستان'},
                    {id: 'UG', text: 'أوغندا'},
                    {id: 'UA', text: 'أوكرانيا'},
                    {id: 'IE', text: 'أيرلندا'},
                    {id: 'IS', text: 'أيسلندا'},
                    {id: 'ET', text: 'اثيوبيا'},
                    {id: 'ER', text: 'اريتريا'},
                    {id: 'EE', text: 'استونيا'},
                    {id: 'IL', text: 'اسرائيل'},
                    {id: 'AR', text: 'الأرجنتين'},
                    {id: 'JO', text: 'الأردن'},
                    {id: 'EC', text: 'الاكوادور'},
                    {id: 'AE', text: 'الامارات العربية ا'},
                    {id: 'BS', text: 'الباهاما'},
                    {id: 'BH', text: 'البحرين'},
                    {id: 'BR', text: 'البرازيل'},
                    {id: 'PT', text: 'البرتغال'},
                    {id: 'BA', text: 'البوسنة والهرسك'},
                    {id: 'GA', text: 'الجابون'},
                    {id: 'ME', text: 'الجبل الأسود'},
                    {id: 'DZ', text: 'الجزائر'},
                    {id: 'DK', text: 'الدانمرك'},
                    {id: 'CV', text: 'الرأس الأخضر'},
                    {id: 'SV', text: 'السلفادور'},
                    {id: 'SN', text: 'السنغال'},
                    {id: 'SD', text: 'السودان'},
                    {id: 'SE', text: 'السويد'},
                    {id: 'EH', text: 'الصحراء الغربية'},
                    {id: 'SO', text: 'الصومال'},
                    {id: 'CN', text: 'الصين'},
                    {id: 'IQ', text: 'العراق'},
                    {id: 'VA', text: 'الفاتيكان'},
                    {id: 'PH', text: 'الفيلبين'},
                    {id: 'AQ', text: 'القطب الجنوبي'},
                    {id: 'CM', text: 'الكاميرون'},
                    {id: 'CG', text: 'الكونغو - برازافيل'},
                    {id: 'KW', text: 'الكويت'},
                    {id: 'HU', text: 'المجر'},
                    {id: 'IO', text: 'المحيط الهندي البر'},
                    {id: 'MA', text: 'المغرب'},
                    {id: 'TF', text: 'المقاطعات الجنوبية'},
                    {id: 'MX', text: 'المكسيك'},
                    {id: 'SA', text: 'المملكة العربية ال'},
                    {id: 'GB', text: 'المملكة المتحدة'},
                    {id: 'NO', text: 'النرويج'},
                    {id: 'AT', text: 'النمسا'},
                    {id: 'NE', text: 'النيجر'},
                    {id: 'IN', text: 'الهند'},
                    {id: 'US', text: 'الولايات المتحدة ا'},
                    {id: 'JP', text: 'اليابان'},
                    {id: 'YE', text: 'اليمن'},
                    {id: 'GR', text: 'اليونان'},
                    {id: 'ID', text: 'اندونيسيا'},
                    {id: 'IR', text: 'ايران'},
                    {id: 'IT', text: 'ايطاليا'},
                    {id: 'PG', text: 'بابوا غينيا الجديد'},
                    {id: 'PY', text: 'باراجواي'},
                    {id: 'PK', text: 'باكستان'},
                    {id: 'PW', text: 'بالاو'},
                    {id: 'BW', text: 'بتسوانا'},
                    {id: 'PN', text: 'بتكايرن'},
                    {id: 'BB', text: 'بربادوس'},
                    {id: 'BM', text: 'برمودا'},
                    {id: 'BN', text: 'بروناي'},
                    {id: 'BE', text: 'بلجيكا'},
                    {id: 'BG', text: 'بلغاريا'},
                    {id: 'BZ', text: 'بليز'},
                    {id: 'BD', text: 'بنجلاديش'},
                    {id: 'PA', text: 'بنما'},
                    {id: 'BJ', text: 'بنين'},
                    {id: 'BT', text: 'بوتان'},
                    {id: 'PR', text: 'بورتوريكو'},
                    {id: 'BF', text: 'بوركينا فاسو'},
                    {id: 'BI', text: 'بوروندي'},
                    {id: 'PL', text: 'بولندا'},
                    {id: 'BO', text: 'بوليفيا'},
                    {id: 'PF', text: 'بولينيزيا الفرنسية'},
                    {id: 'PE', text: 'بيرو'},
                    {id: 'TZ', text: 'تانزانيا'},
                    {id: 'TH', text: 'تايلند'},
                    {id: 'TW', text: 'تايوان'},
                    {id: 'TM', text: 'تركمانستان'},
                    {id: 'TR', text: 'تركيا'},
                    {id: 'TT', text: 'ترينيداد وتوباغو'},
                    {id: 'TD', text: 'تشاد'},
                    {id: 'TG', text: 'توجو'},
                    {id: 'TV', text: 'توفالو'},
                    {id: 'TK', text: 'توكيلو'},
                    {id: 'TO', text: 'تونجا'},
                    {id: 'TN', text: 'تونس'},
                    {id: 'TL', text: 'تيمور الشرقية'},
                    {id: 'JM', text: 'جامايكا'},
                    {id: 'GI', text: 'جبل طارق'},
                    {id: 'GD', text: 'جرينادا'},
                    {id: 'GL', text: 'جرينلاند'},
                    {id: 'AX', text: 'جزر أولان'},
                    {id: 'AN', text: 'جزر الأنتيل الهولن'},
                    {id: 'TC', text: 'جزر الترك وجايكوس'},
                    {id: 'KM', text: 'جزر القمر'},
                    {id: 'KY', text: 'جزر الكايمن'},
                    {id: 'MH', text: 'جزر المارشال'},
                    {id: 'MV', text: 'جزر الملديف'},
                    {id: 'UM', text: 'جزر الولايات المتح'},
                    {id: 'SB', text: 'جزر سليمان'},
                    {id: 'FO', text: 'جزر فارو'},
                    {id: 'VI', text: 'جزر فرجين الأمريكي'},
                    {id: 'VG', text: 'جزر فرجين البريطان'},
                    {id: 'FK', text: 'جزر فوكلاند'},
                    {id: 'CK', text: 'جزر كوك'},
                    {id: 'CC', text: 'جزر كوكوس'},
                    {id: 'MP', text: 'جزر ماريانا الشمال'},
                    {id: 'WF', text: 'جزر والس وفوتونا'},
                    {id: 'CX', text: 'جزيرة الكريسماس'},
                    {id: 'BV', text: 'جزيرة بوفيه'},
                    {id: 'IM', text: 'جزيرة مان'},
                    {id: 'NF', text: 'جزيرة نورفوك'},
                    {id: 'HM', text: 'جزيرة هيرد وماكدون'},
                    {id: 'CF', text: 'جمهورية افريقيا ال'},
                    {id: 'CZ', text: 'جمهورية التشيك'},
                    {id: 'DO', text: 'جمهورية الدومينيك'},
                    {id: 'CD', text: 'جمهورية الكونغو ال'},
                    {id: 'ZA', text: 'جمهورية جنوب افريق'},
                    {id: 'GT', text: 'جواتيمالا'},
                    {id: 'GP', text: 'جوادلوب'},
                    {id: 'GU', text: 'جوام'},
                    {id: 'GE', text: 'جورجيا'},
                    {id: 'GS', text: 'جورجيا الجنوبية وج'},
                    {id: 'DJ', text: 'جيبوتي'},
                    {id: 'JE', text: 'جيرسي'},
                    {id: 'DM', text: 'دومينيكا'},
                    {id: 'RW', text: 'رواندا'},
                    {id: 'RU', text: 'روسيا'},
                    {id: 'BY', text: 'روسيا البيضاء'},
                    {id: 'RO', text: 'رومانيا'},
                    {id: 'RE', text: 'روينيون'},
                    {id: 'ZM', text: 'زامبيا'},
                    {id: 'ZW', text: 'زيمبابوي'},
                    {id: 'CI', text: 'ساحل العاج'},
                    {id: 'WS', text: 'ساموا'},
                    {id: 'AS', text: 'ساموا الأمريكية'},
                    {id: 'SM', text: 'سان مارينو'},
                    {id: 'PM', text: 'سانت بيير وميكولون'},
                    {id: 'VC', text: 'سانت فنسنت وغرنادي'},
                    {id: 'KN', text: 'سانت كيتس ونيفيس'},
                    {id: 'LC', text: 'سانت لوسيا'},
                    {id: 'MF', text: 'سانت مارتين'},
                    {id: 'SH', text: 'سانت هيلنا'},
                    {id: 'ST', text: 'ساو تومي وبرينسيبي'},
                    {id: 'LK', text: 'سريلانكا'},
                    {id: 'SJ', text: 'سفالبارد وجان مايا'},
                    {id: 'SK', text: 'سلوفاكيا'},
                    {id: 'SI', text: 'سلوفينيا'},
                    {id: 'SG', text: 'سنغافورة'},
                    {id: 'SZ', text: 'سوازيلاند'},
                    {id: 'SY', text: 'سوريا'},
                    {id: 'SR', text: 'سورينام'},
                    {id: 'CH', text: 'سويسرا'},
                    {id: 'SL', text: 'سيراليون'},
                    {id: 'SC', text: 'سيشل'},
                    {id: 'CL', text: 'شيلي'},
                    {id: 'RS', text: 'صربيا'},
                    {id: 'CS', text: 'صربيا والجبل الأسو'},
                    {id: 'TJ', text: 'طاجكستان'},
                    {id: 'OM', text: 'عمان'},
                    {id: 'GM', text: 'غامبيا'},
                    {id: 'GH', text: 'غانا'},
                    {id: 'GF', text: 'غويانا'},
                    {id: 'GY', text: 'غيانا'},
                    {id: 'GN', text: 'غينيا'},
                    {id: 'GQ', text: 'غينيا الاستوائية'},
                    {id: 'GW', text: 'غينيا بيساو'},
                    {id: 'VU', text: 'فانواتو'},
                    {id: 'FR', text: 'فرنسا'},
                    {id: 'PS', text: 'فلسطين'},
                    {id: 'VE', text: 'فنزويلا'},
                    {id: 'FI', text: 'فنلندا'},
                    {id: 'VN', text: 'فيتنام'},
                    {id: 'FJ', text: 'فيجي'},
                    {id: 'CY', text: 'قبرص'},
                    {id: 'KG', text: 'قرغيزستان'},
                    {id: 'QA', text: 'قطر'},
                    {id: 'KZ', text: 'كازاخستان'},
                    {id: 'NC', text: 'كاليدونيا الجديدة'},
                    {id: 'HR', text: 'كرواتيا'},
                    {id: 'KH', text: 'كمبوديا'},
                    {id: 'CA', text: 'كندا'},
                    {id: 'CU', text: 'كوبا'},
                    {id: 'KR', text: 'كوريا الجنوبية'},
                    {id: 'KP', text: 'كوريا الشمالية'},
                    {id: 'CR', text: 'كوستاريكا'},
                    {id: 'CO', text: 'كولومبيا'},
                    {id: 'KI', text: 'كيريباتي'},
                    {id: 'KE', text: 'كينيا'},
                    {id: 'LV', text: 'لاتفيا'},
                    {id: 'LA', text: 'لاوس'},
                    {id: 'LB', text: 'لبنان'},
                    {id: 'LU', text: 'لوكسمبورج'},
                    {id: 'LY', text: 'ليبيا'},
                    {id: 'LR', text: 'ليبيريا'},
                    {id: 'LT', text: 'ليتوانيا'},
                    {id: 'LI', text: 'ليختنشتاين'},
                    {id: 'LS', text: 'ليسوتو'},
                    {id: 'MQ', text: 'مارتينيك'},
                    {id: 'MO', text: 'ماكاو الصينية'},
                    {id: 'MT', text: 'مالطا'},
                    {id: 'ML', text: 'مالي'},
                    {id: 'MY', text: 'ماليزيا'},
                    {id: 'YT', text: 'مايوت'},
                    {id: 'MG', text: 'مدغشقر'},
                    {id: 'EG', text: 'مصر'},
                    {id: 'MK', text: 'مقدونيا'},
                    {id: 'MW', text: 'ملاوي'},
                    {id: 'ZZ', text: 'منطقة غير معرفة'},
                    {id: 'MN', text: 'منغوليا'},
                    {id: 'MR', text: 'موريتانيا'},
                    {id: 'MU', text: 'موريشيوس'},
                    {id: 'MZ', text: 'موزمبيق'},
                    {id: 'MD', text: 'مولدافيا'},
                    {id: 'MC', text: 'موناكو'},
                    {id: 'MS', text: 'مونتسرات'},
                    {id: 'MM', text: 'ميانمار'},
                    {id: 'FM', text: 'ميكرونيزيا'},
                    {id: 'NA', text: 'ناميبيا'},
                    {id: 'NR', text: 'نورو'},
                    {id: 'NP', text: 'نيبال'},
                    {id: 'NG', text: 'نيجيريا'},
                    {id: 'NI', text: 'نيكاراجوا'},
                    {id: 'NZ', text: 'نيوزيلاندا'},
                    {id: 'NU', text: 'نيوي'},
                    {id: 'HT', text: 'هايتي'},
                    {id: 'HN', text: 'هندوراس'},
                    {id: 'NL', text: 'هولندا'},
                    {id: 'HK', text: 'هونج كونج الصينية'},
                ];

                function formatCountry(country) {
                    if (!country.id) {
                        return country.text;
                    }
                    var $country = $(
                        '<span class="flag-icon flag-icon-' + country.id.toLowerCase() + ' flag-icon-squared"></span>' +
                        '<span class="flag-text">' + country.text + "</span>"
                    );
                    return $country;
                };

                //Assuming you have a select element with name country
                // e.g. <select name="name"></select>

                $("[name='country']").select2({
                    placeholder: "{{ trans('admin.select_country') }}",
                    templateResult: formatCountry,
                    data: isoCountries
                });


            });
        })(jQuery);
    </script>
@endpush
@include('admin.layouts.footer')
